### ISSUE TITLE
 Check failed: bottom[i]->shape() == bottom[0]->shape() 

### ISSUE THREAD

**Issue by kexul** [thesby/CRFasRNN-merge#1]
Hi,I followed your instruction and merged it with a HED modified caffe,I placed the crf layer behind the last conv layer of [HED](https://github.com/s9xie/hed) ,but encountered this error 
`F0420 16:20:45.094352 23651 eltwise_layer.cpp:34] Check failed: bottom[i]->shape() == bottom[0]->shape() ` 

my output before the crf layer is `1*1*576*768` and the data size if` 1*3*576*768`.

there is no eltwise layer used in the previous layers,so I wonder it may happen in the meanfiled layer? 
I've read  your  [blog](http://3dmoscow.ru/an.php?session_new=aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdGhlc2J5L2FydGljbGUvZGV0YWlscy81MTU5MzU5MSNjb21tZW50cw$?) ,still can't figure out what's happening here,,,could your please deliver some help?

Thanks in advance!

**Comment by justStarG** [comment]
if you want to use eltwise layer, you should make the size the same. As you described, the channel number of the output of crf and the data is different.

**Comment by kexul** [comment]
Thank you  for reply,I've solved this problem by setting the image size `500*500`.
